- name: Destroy
  hosts: localhost
  connection: local
  collections:
  - kubernetes.core
  tasks:

  - name: Remove OSSMPlugin CR
    vars:
      custom_resource: "{{ lookup('template', cr_file_path) | from_yaml }}"
    k8s:
      state: absent
      api_version: kiali.io/v1alpha1
      kind: OSSMPlugin
      namespace: "{{ cr_namespace }}"
      name: "{{ custom_resource.metadata.name }}"
      wait: yes
      wait_timeout: 600
    ignore_errors: yes

  - name: Remove the cr namespace
    k8s:
      state: absent
      api_version: v1
      kind: Namespace
      name: "{{ cr_namespace }}"

  - name: Remove the install namespace
    k8s:
      state: absent
      api_version: v1
      kind: Namespace
      name: "{{ ossmplugin.install_namespace }}"
    when:
    - ossmplugin.install_namespace != cr_namespace
