---
dependency:
  name: galaxy
driver:
  name: $DORP
platforms:
- name: default
  groups:
  - k8s
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_enabled: junit
  playbooks:
    destroy: ../default/destroy.yml
    prepare: ../default/prepare.yml
    cleanup: ../default/cleanup.yml
  inventory:
    group_vars:
      all:
        cr_file_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/ossmplugin-cr.yaml"
        cr_namespace: "{{ 'ossmplugin' }}"
        wait_retries: "{{ lookup('env', 'MOLECULE_WAIT_RETRIES') | default('360', True) }}"
        plugin_image_pull_secret_json: "{{ lookup('env', 'PLUGIN_IMAGE_PULL_SECRET_JSON') | default('') }}"
        ossmplugin:
          spec_version: "{{ lookup('env', 'MOLECULE_OSSMPLUGIN_CR_SPEC_VERSION') | default('default', True) }}"
          install_namespace: "ossmplugin"
          operator_namespace: "{{ 'openshift-operators' }}"
          image_name: "{{ 'image-registry.openshift-image-registry.svc:5000/kiali/servicemesh-plugin' if lookup('env', 'MOLECULE_OSSMPLUGIN_IMAGE_NAME') == 'dev' else ('quay.io/kiali/servicemesh-plugin' if ansible_env.MOLECULE_OSSMPLUGIN_IMAGE_NAME is not defined else lookup('env', 'MOLECULE_OSSMPLUGIN_IMAGE_NAME')) }}"
          image_version: "{{ 'latest' if ansible_env.MOLECULE_OSSMPLUGIN_IMAGE_VERSION is not defined else lookup('env', 'MOLECULE_OSSMPLUGIN_IMAGE_VERSION') }}"
scenario:
  name: default
  test_sequence:
  - prepare
  - converge
  - destroy
