apiVersion: kiali.io/v1alpha1
kind: OSSMPlugin
metadata:
  name: ossmplugin
spec:
  version: "{{ ossmplugin.spec_version }}"
  deployment:
    imageName: "{{ ossmplugin.image_name }}"
    imageVersion: "{{ ossmplugin.image_version }}"
    imagePullPolicy: Always
    imagePullSecrets: [ {{ plugin_image_pull_secret_name | default('') }} ]
